### ISSUE TITLE
Newest update causing crafting loops to crash

### ISSUE THREAD

**Issue by Glorou** [Jaksuhn/SomethingNeedDoingLegacy#172]
As the title says, when trying to do a normal infinite macro the follow error appears in xllogs and the script refuses to run, version 1.22.0.0
```
06:24:15.255 | ERR | [SomethingNeedDoing] Unexpected error
	System.IndexOutOfRangeException: Index was outside the bounds of the array.
	   at SomethingNeedDoing.Grammar.Commands.ClickCommand.Parse(String text) in /home/runner/work/SomethingNeedDoing/SomethingNeedDoing/SomethingNeedDoing/Grammar/Commands/ClickCommand.cs:line 38
	   at SomethingNeedDoing.Grammar.MacroParser.ParseLine(String line) in /home/runner/work/SomethingNeedDoing/SomethingNeedDoing/SomethingNeedDoing/Grammar/MacroParser.cs:line 58
	   at SomethingNeedDoing.Grammar.MacroParser.Parse(String macroText)+MoveNext() in /home/runner/work/SomethingNeedDoing/SomethingNeedDoing/SomethingNeedDoing/Grammar/MacroParser.cs:line 34
	   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	   at SomethingNeedDoing.Misc.ActiveMacro..ctor(MacroNode node) in /home/runner/work/SomethingNeedDoing/SomethingNeedDoing/SomethingNeedDoing/Misc/ActiveMacro.cs:line 37
	   at SomethingNeedDoing.Managers.MacroManager.EnqueueMacro(MacroNode node) in /home/runner/work/SomethingNeedDoing/SomethingNeedDoing/SomethingNeedDoing/Managers/MacroManager.cs:line 205
	   at SomethingNeedDoing.Interface.MacroWindow.RunMacro(MacroNode node) in /home/runner/work/SomethingNeedDoing/SomethingNeedDoing/SomethingNeedDoing/Interface/MacroWindow.cs:line 570
```

**Comment by Jaksuhn** [comment]
fixed
